---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-4
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: rbd-csi
